#!/bin/bash

kubeconfig=/etc/kubernetes/admin.conf

if [ -e "$kubeconfig" ]; then
    pod=$1
    if [ "$pod"x = ""x ]; then
    kubectl --kubeconfig=$kubeconfig get pod --all-namespaces -o wide
    else
    kubectl --kubeconfig=$kubeconfig get pod --all-namespaces -o wide | grep $pod
    fi
else
    echo "$kubeconfig认证文件不存在"
fi



