#!/bin/bash

kubeconfig=/etc/kubernetes/admin.conf

if [ -e "$kubeconfig" ]; then
    svc=$1
    if [ "$svc"x = ""x ]; then
    kubectl --kubeconfig=$kubeconfig get svc --all-namespaces -o wide
    else
    kubectl --kubeconfig=$kubeconfig get svc --all-namespaces -o wide | grep $svc
    fi
else
    echo "$kubeconfig认证文件不存在"
fi
